name: Deploy PR with comment

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
          check-latest: true

      - name: Build
        run: go build -v ./...

  release:
    name: Build and push docker image to docker hub
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == '/deploy' }}
    needs: [build]
    environment: dev
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker(tags, labels) from Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: bilginyuksel/gotemplate

      - name: Build and push docker image
        uses: docker/build-push-action@master
        with:
          context: .
          push: true
<<<<<<< Updated upstream
          tags: dev-${{ github.event.issue.id }}
          labels: dev
=======
          tags: dev-#${{ github.event.issue.id }}
          labels: ${{ steps.meta.outputs.labels }}
>>>>>>> Stashed changes
